version: '3.7'

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  jaeger:
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9412:9411" 
    networks:
      - grafana
    image: jaegertracing/all-in-one:1.6
  grafana:
    ports:
      - 3000:3000
    networks:
      - grafana
    image: grafana/grafana-oss:latest
    depends_on:
      - jaeger

networks:
  grafana:
    driver: bridge